/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.AdminstrativeRole;

import Business.PersonDirectory;
import Business.UserAccountDirectory;
import UserInterface.UserAccount.ManageUserAccountDirectoryJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Rushabh
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final PersonDirectory personDirectory;
    private final UserAccountDirectory userAccountDirectory;
    
    /** Creates new form AdminWorkAreaJPanel
     * @param userProcessContainer
     * @param personDirectory
     * @param userAccountDirectory
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,PersonDirectory personDirectory,UserAccountDirectory userAccountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.userAccountDirectory = userAccountDirectory;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managesuppliersButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageCustomerButton = new javax.swing.JButton();
        manageUserButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managesuppliersButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        managesuppliersButton1.setText("Manage Suppliers >>");
        managesuppliersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managesuppliersButton1ActionPerformed(evt);
            }
        });
        add(managesuppliersButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 260, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        manageCustomerButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageCustomerButton.setText("Manage Customer >>");
        manageCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerButtonActionPerformed(evt);
            }
        });
        add(manageCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 260, -1));

        manageUserButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageUserButton.setText("Manage User Account >>");
        manageUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserButtonActionPerformed(evt);
            }
        });
        add(manageUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void managesuppliersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managesuppliersButton1ActionPerformed
        // TODO add your handling code here:
        ManageSuppliers manageSuppliers = new ManageSuppliers(userProcessContainer, personDirectory.getSupplierDirectory());
        userProcessContainer.add("ManageSuppliers", manageSuppliers);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managesuppliersButton1ActionPerformed

    private void manageCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerButtonActionPerformed
        // TODO add your handling code here:
        ManageCustomerJPanel manageCustomerJPanel = new ManageCustomerJPanel(userProcessContainer, personDirectory.getCustomerDirectory());
        userProcessContainer.add("ManageCustomerJPanel", manageCustomerJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomerButtonActionPerformed

    private void manageUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountDirectoryJPanel manageUserAccountDirectoryJPanel = new ManageUserAccountDirectoryJPanel(userProcessContainer,userAccountDirectory,personDirectory);
        userProcessContainer.add("ManageUserAccountDirectoryJPanel", manageUserAccountDirectoryJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCustomerButton;
    private javax.swing.JButton manageUserButton;
    private javax.swing.JButton managesuppliersButton1;
    // End of variables declaration//GEN-END:variables
    
}
