/*
 * Class : SalesWorkAreaJPanel.java
 * Developer : Laksh Lumba
 * Reviewer :
 * Description : 
 * Created On : Nov 2, 2014, 10:44:04 PM
 * ---------------------------------------------------------------------------
 * Change History
 * Develper :
 * Reviwer :
 * Changed ON :
 * ---------------------------------------------------------------------------
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sales;

import Business.business.Business;
import Business.customer.CustomerDirectory;
import Business.organization.Organization;
import Business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Laksh
 */
public class SalesWorkAreaJPanel extends javax.swing.JPanel {
    private final Business business;
    private final JPanel userProcessContainer;
    private final Organization organization;
    private final CustomerDirectory customerDirectory;
    private final UserAccount userAccount;

    /**
     * Creates new form SalesWorkAreaJPanel
     * @param userProcessContainer
     * @param userAccount
     * @param organization
     * @param business
     * @param customerDirectory
     */
    public SalesWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Business business,CustomerDirectory customerDirectory) {
        initComponents();
        this.business = business;
        this.customerDirectory = customerDirectory;
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageCustomerRequestButton = new javax.swing.JButton();
        manageSupplierRequestButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Sales Work Area");

        manageCustomerRequestButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageCustomerRequestButton.setText("Manage Customer Request");
        manageCustomerRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerRequestButtonActionPerformed(evt);
            }
        });

        manageSupplierRequestButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageSupplierRequestButton.setText("Manage Supplier Request");
        manageSupplierRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSupplierRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(manageSupplierRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(manageCustomerRequestButton))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(manageCustomerRequestButton)
                .addGap(46, 46, 46)
                .addComponent(manageSupplierRequestButton)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageCustomerRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerRequestButtonActionPerformed
        ManageCustomerRequestJPanel manageCustomerRequestJPanel = new ManageCustomerRequestJPanel(userProcessContainer,customerDirectory);
        userProcessContainer.add("ManageCustomerRequestJPanel",manageCustomerRequestJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomerRequestButtonActionPerformed

    private void manageSupplierRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSupplierRequestButtonActionPerformed
        ManageSupplierRequestJPanel manageSupplierRequestJPanel = new ManageSupplierRequestJPanel(userProcessContainer,userAccount,organization);
        userProcessContainer.add("ManageSupplierRequestJPanel",manageSupplierRequestJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_manageSupplierRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCustomerRequestButton;
    private javax.swing.JButton manageSupplierRequestButton;
    // End of variables declaration//GEN-END:variables
}
