/*
 * Developer : 
 * Reviewer :
 * and open the template in the editor.
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.customer;


import Business.supplier.SupplierDirectory;
import Business.customer.Customer;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Laksh
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {
    private final JPanel userProcessContainer;
    private final SupplierDirectory supplierDirectory;
    private final Customer customer;
    /**
     * Creates new form CustomerWorkAreaJPanel
     * @param userProcessContainer
     * @param supplierDirectory
     * @param customer
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer,SupplierDirectory supplierDirectory,Customer customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        this.customer = customer;
        populateCustomerID();        
    }
    private void populateCustomerID(){
        customerIDTextField.setText(String.valueOf(customer.getPersonId()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        browseProductButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        customerIDTextField = new javax.swing.JTextField();
        viewOrderStatusButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Browse Product Catatog");

        browseProductButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        browseProductButton.setText("Browse Product");
        browseProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseProductButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Login Customer ID");

        customerIDTextField.setEditable(false);

        viewOrderStatusButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        viewOrderStatusButton.setText("Check Order Status");
        viewOrderStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(customerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(browseProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewOrderStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(browseProductButton)
                .addGap(27, 27, 27)
                .addComponent(viewOrderStatusButton)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseProductButtonActionPerformed
        // TODO add your handling code here:
        BrowseProductJPanel browseProductJPanel = new BrowseProductJPanel(userProcessContainer,supplierDirectory,customer);
        userProcessContainer.add("BrowseProductJPanel",browseProductJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_browseProductButtonActionPerformed

    private void viewOrderStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderStatusButtonActionPerformed
        ViewOrderJPanel viewOrderJPanel = new ViewOrderJPanel(userProcessContainer,customer);
        userProcessContainer.add("ViewOrderJPanel",viewOrderJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrderStatusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseProductButton;
    private javax.swing.JTextField customerIDTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton viewOrderStatusButton;
    // End of variables declaration//GEN-END:variables
}
