/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.neu.css.view;

import com.neu.css.model.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Laksh
 */
public class ManageAccountWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProocessContainer;
    private AccountDirectory accountDirectory;
    /**
     * Creates new form ManaageAccountWorkAreaJPanel
     */
    public ManageAccountWorkAreaJPanel(JPanel jPanel, AccountDirectory accountDirectory) {
        initComponents();
        this.userProocessContainer = jPanel;
        this.accountDirectory = accountDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountButton = new javax.swing.JButton();
        manageAccountButton = new javax.swing.JButton();

        createAccountButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        manageAccountButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        manageAccountButton.setText("Manage Account");
        manageAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(createAccountButton)
                .addGap(38, 38, 38)
                .addComponent(manageAccountButton)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        // TODO add your handling code here:
        CreateAccountJPanel createAccountJPanel = new CreateAccountJPanel(userProocessContainer, accountDirectory);
        userProocessContainer.add("CreateAccountJPanel",createAccountJPanel);
        CardLayout cardLayout = (CardLayout)userProocessContainer.getLayout();
        cardLayout.next(userProocessContainer);
        
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void manageAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountButtonActionPerformed
        // TODO add your handling code here:
        ManageAccountJPanel manageAccountJPanel = new ManageAccountJPanel(userProocessContainer, accountDirectory);
        userProocessContainer.add("ManageAccountJPanel",manageAccountJPanel);
        CardLayout cardLayout = (CardLayout)userProocessContainer.getLayout();
        cardLayout.next(userProocessContainer);
    }//GEN-LAST:event_manageAccountButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccountButton;
    private javax.swing.JButton manageAccountButton;
    // End of variables declaration//GEN-END:variables
}
