/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UserInterface.SupplierRole;

import Business.organization.Organization;
import Business.organization.SalesOrganization;
import Business.supplier.Supplier;
import Business.useraccount.UserAccount;
import Business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final Supplier supplier;
    private final SalesOrganization salesOrganization;
    private final UserAccount userAccount;
    
    /** Creates new form ProductManagerWorkAreaJPanel
     * @param userProcessContainer
     * @param supplier
     * @param userAccount
     * @param organization */
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, Supplier supplier,UserAccount userAccount,Organization organization) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.supplier = supplier;
       this.salesOrganization = (SalesOrganization)organization;
       this.userAccount = userAccount;
       enableSupplier();
    }
    private void enableSupplier()
    {
       manageProductButton.setEnabled(false);
       reviewProductButton.setEnabled(false);
       enrollButton.setEnabled(true);
       for (WorkRequest workRequest : salesOrganization.getWorkQueue().getWorkRequestList()){
           UserAccount userAccount1 = workRequest.getSender();
           if (null !=  userAccount1 && null !=  userAccount1.getPerson()){
            if((userAccount1.getPerson().getPersonId() == userAccount.getPerson().getPersonId()) && workRequest.getStatus().equals("Approved")){
                manageProductButton.setEnabled(true);
                reviewProductButton.setEnabled(true);
                enrollButton.setEnabled(false);
            }
           }
       }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageProductButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        reviewProductButton = new javax.swing.JButton();
        enrollButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("My Work Area (Product Manager Role)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        manageProductButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        manageProductButton.setText("Manage Product Catalog >>");
        manageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductButtonActionPerformed(evt);
            }
        });
        add(manageProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton2.setText("Update Personal Profile >>");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 260, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton3.setText("Manage Staff");
        jButton3.setEnabled(false);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 260, -1));

        reviewProductButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        reviewProductButton.setText("Review Product Performance >>");
        reviewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewProductButtonActionPerformed(evt);
            }
        });
        add(reviewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, -1));

        enrollButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        enrollButton.setText("Enroll Me >>");
        enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollButtonActionPerformed(evt);
            }
        });
        add(enrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void manageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductButtonActionPerformed
        // TODO add your handling code here:
       ManageProductCatalogJPanel manageProductCatalogJPanel = new ManageProductCatalogJPanel(userProcessContainer, supplier);
       userProcessContainer.add("ManageProductCatalogJPanel",manageProductCatalogJPanel);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductButtonActionPerformed

    private void reviewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewProductButtonActionPerformed
        // TODO add your handling code here:
        ProductSalesReviewJPanel productSalesReviewJPanel = new ProductSalesReviewJPanel(userProcessContainer, supplier);
        userProcessContainer.add("ProductSalesReviewJPanel", productSalesReviewJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reviewProductButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollButtonActionPerformed
        SupplierEnrollmentJPanel supplierEnrollmentJPanel = new SupplierEnrollmentJPanel(userProcessContainer,userAccount,salesOrganization);
        userProcessContainer.add("SupplierEnrollmentJPanel", supplierEnrollmentJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_enrollButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrollButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageProductButton;
    private javax.swing.JButton reviewProductButton;
    // End of variables declaration//GEN-END:variables
}
